# PyTorch Basic Tensor Manipulation 2

In [13]:
import torch

# Shape를 자유자재로 바꿀 수 있어야 한다.

## View (Reshape)

다시 모양을 만들어 주겠다 / View 함수를 이용해 Matrix를 원하는 형태로 만들 수 있는데, 이것을 잘하는 것이 딥러닝의 중요한 요소

In [43]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
             
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [46]:
print(ft.view([-1, 3]))       # 모양을 바꿔줌 (2개의 차원을 가지는데 '-1 : 앞에는 모르겠고, 3: 두 번째 차원은 3개 )
print(ft.view([-1, 3]).shape) # |ft| = (2, 2, 3) -> |ft| = (2x2, 3) = (4, 3) 4 by 3

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [45]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape) # 4 x 1 x 3 = 12개의 Element가 잘 들어있는 것을 확인

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

자동으로 내가 원하는 dimension에 혹은 내가 원하는 전체에서 하나만 남아있는 경우 없애주는 것

In [4]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft) # |ft| = (3, 1) // 3 x 1
print(ft.shape) # (3, )

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [6]:
print(ft.squeeze()) # squeeze(dim = ?) 해당 dimension에 1이 있을 경우 없앤다 
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

Squeeze를 반대로! __dimension을 꼭 명시해주어야 함__

In [10]:
ft = torch.Tensor([0, 1, 2]) # |ft| = (3, )
print(ft.shape)

torch.Size([3])


In [17]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [14]:
print(ft.view(1, -1)) # (3, ) -> (3, 1)
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [20]:
print(ft.unsqueeze(-1)) # 마지막(두 번째) dimension
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

Tensor의 type을 바꿔주겠다!

In [21]:
lt = torch.LongTensor([1, 2, 3, 4]) # long으로 선언
print(lt)

tensor([1, 2, 3, 4])


In [22]:
print(lt.float()) #float로 바꿈

tensor([1., 2., 3., 4.])


byte Tensor 같은 경우는 조건문을 실행했을 때

ex) bt = (lt == 3) -> bt = (0, 0, 1, 0)

In [23]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [25]:
print(bt.long())  #long 으로 바꿈
print(bt.float()) #float 로 바꿈

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

이어붙이기

In [28]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]]) # x와 y는 2 x 2 로 크기가 같음

In [30]:
print(torch.cat([x, y], dim = 0)) # cat의 dimension 0 이 늘어남 -> (4, 2) = 4 x 2
print(torch.cat([x, y], dim = 1)) # cat의 dimension 1 이 늘어남 -> (2, 4) = 2 x 4

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

Concatenation을 조금 더 편리하게 사용할 수 있도록 단축해 놓은 것

In [31]:
x = torch.FloatTensor([1, 4])  # |x| = |y| = |z|
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [32]:
print(torch.stack([x, y, z])) # Tensor들을 Stack에 쌓아라 -> 3 x 2 // 아래와 같이 Unsqueeze를 활용해 나타낼 수 있다.
print(torch.stack([x, y, z], dim = 1)) # dimension 1에 대해서 쌓아라 -> 2 x 3

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [33]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [35]:
x = torch.FloatTensor([[0, 1, 2],[2, 1, 0]]) # 2x3의 Tensor 선언
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [36]:
print(torch.ones_like(x))  # 똑같은 size에 1로 가득찬 Matrix
print(torch.zeros_like(x)) # 똑같은 size에 0으로 가득찬 Matrix

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


__이것들의 device도 똑같이 갈 것이다!!!!__

같은 device에 있어야만 연산이 가능

## In-place Operation

기본적으로 곱하기를 해주는 것인데  _ (under bar)가 붙는다.

다만 메모리를 새로 선언하지 않고 정답값을 기존의 Tensor에 넣는다. => 좀 더 속도가 빠른 것을 추측할 수 있음
(하지만 솔직히 파이토치에서 --가 잘 설계되어 있어서 속도적 이점이 딱이 없을 수 있음)

In [40]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [42]:
print(x.mul(2.)) # <= X x 2 임의의 메모리로 값이 들어가 출력함
print(x) # <= 값이 변하지 않음
print(x.mul_(2.))
print(x) # <= x에 결과값이 저장된 것을 확인할 수 있음

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
