# PyTorch Basic Tensor Manipulation 1

In [1]:
import numpy as np # numpy를 np라고 import
#numpy와 pytorch는 굉장히 호환성이 높고 직관적
import torch

## 1D Array with NumPy

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.]) #numpy vector 선언
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank  of t: ', t.ndim) # 몇개 차원으로 이루어져 있는가? -> vector
print('Shape of t: ', t.shape) # shape는 어떤가? -> 하나에 차원에 대해 7개의 element가 들어있다.

Rank  of t:  1
Shape of t:  (7,)


In [5]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) #Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   #Slicing
print('t[:2] t[3:]', t[:2], t[3:])             #Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] [0. 1.] [3. 4. 5. 6.]


## 2D Array with NumPy

In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]]) # 2차원
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank  of t: ', t.ndim) # 몇개 차원으로 이루어져 있는가? -> 2차원
print('Shape of t: ', t.shape) # shape는 어떤가? -> 각각의 차원에 4개와 3개의 Element가 들어가 있다.

Rank  of t:  2
Shape of t:  (4, 3)


## 1D Array with PyTorch

In [10]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.]) # Torch에 Float형 Tensor로 값을 만들겠다.
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim())  #rank 몇개의 차원이 있는가?
print(t.shape)  #shape 모양은 어떻니? -> 한 개의 차원에는 7개의 Element가 있다.
print(t.size()) #shape
print(t[0], t[1], t[-1]) # Elenment에 접근
print(t[2:5], t[4:-1])   #Slicing
print(t[:2], t[3:])      #Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [17]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t) # 4 by 3 Matrix 출력

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [19]:
print(t.dim())   # rank
print(t.size())  # shape
print(t[:, 1])   # 첫 번째 차원에서는 다 가져오되, 두 번째 차원에서는 첫 번째 것만 가져와라
print(t[:, 1].size())  # 1개의 list 안에 들어있는 Element가 4개
print(t[:, :-1]) # 첫 번째 차원에서는 다 가져오되, 두 번째 차원에서는 마지막 것만 제외한 모든 것을 가져와라

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

자동적으로 Matrix의 크기를 맞춰주는 기능

In [21]:
# Same shape
m1 = torch.FloatTensor([3, 3])
m2 = torch.FloatTensor([2, 2])
print(m1 + m2)

tensor([5., 5.])


In [23]:
# Vector + scalar
m1 = torch.FloatTensor([1, 2])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]] Scalar
print(m1 + m2)

tensor([4., 5.])


In [25]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])   # [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # [[3, 3], [4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication

In [27]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2)
print(m1.mul(m2)) # 2 x 2


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

평균 구하기

In [30]:
t = torch.FloatTensor([1, 2]) 
print(t.mean()) # 평균 구하기!

tensor(2.)


In [31]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also use t.mean for higher rank tensors to get mean of all elements, or mean by paricular dimension

In [32]:
t = torch.FloatTensor([[1, 2], [3, 4]]) #Matrix Tensor 선언
print(t)

tensor([[1., 2.],
        [3., 4.]])


이해가 잘 안돼! dimension의 개념

In [34]:
print(t.mean()) # 전체 Element의 Mean
print(t.mean(dim = 0))  # 첫 번째 dimension의 Mean 출력 <-dimension 0을 없애겠어! :: 결과 [?, ?] vector
print(t.mean(dim = 1))  # 두 번째 dimension의 Mean 출력
print(t.mean(dim = -1)) # 마지막 dimension의 Mean 출력

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [35]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [36]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax

Max : Tensor나 행렬에 대해서 가장 큰 값을 찾아주는 것

Argmax : 그 index값을 return 해 주는 것

In [37]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The max operator returns one value if it is called without an argument.

In [41]:
print(t.max()) # Returns one Value: max

tensor(4.)


The __max__ operator return 2 values when called with dimension specified. The first value is the maximum value, and the second value is the argmax! the index of the element with maximum value

In [40]:
print(t.max(dim = 0)) # Returns two values: max and argmax
print('Max:    ', t.max(dim = 0)[0])
print('Argmax: ', t.max(dim = 0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:     tensor([3., 4.])
Argmax:  tensor([1, 1])


In [42]:
print(t.max(dim = 1))
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
